advance/advance/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('basic_app/', include('basic_app.urls', namespace='basic_app'))
]

advance/basic_app/urls.py
from basic_app import views
from django.urls import path
from django.conf.urls import url

app_name = 'basic_app'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', views.SchoolUpdateView.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', views.SchoolDeleteView.as_view(), name='delete'),
]

advance/basic_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def get_absolute_url(self):
        return reverse("basic_app:detail", kwargs={'pk': self.pk})

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

advance/basic_app/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
# from django.http import HttpResponse
from . import models

# class CBView(View):
# def get(self,request):
# return HttpResponse("CLASS BASED VIEWS ARE COOL!!")


class IndexView(TemplateView):
    template_name = 'index.html'

# def get_context_data(self,**kwargs):
# context = super().get_context_data(**kwargs)
# context['injectme'] = 'BASIC INJECTION!!'
# return context


class SchoolListView(ListView):
    # Aqui defino que schools va a ser una lista de todos los objetos creado en el modelo School
    context_object_name = 'schools'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_details'
    model = models.School
    template_name = 'basic_app/school_detail.html'


class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School


class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("basic_app:list")

advance/basic_app/templates/basic_app/basic_app_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>

    <nav class = "navbar navbar-default navbar-static-top">
      <ul class = "nav navbar-nav">
        <li><a class="navbar-brand" href = "{% url 'basic_app:list' %}">School</a></li>
        <li><a class="navbar-brand" href = "{% url 'admin:index' %}">Admin</a></li>

      </ul>

    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

advance/basic_app/templates/basic_app/school_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Dekete {{school.name}}?</h1>
  <form method="post">
    {% csrf_token %}
    <input type="Submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'basic_app:detail' pk=school.pk %}">Cancel</a>
  </form>
</div>
{% endblock %}

advance/basic_app/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>Welcome to the School Detail Page</h1>
  <h2>School details:</h2>
  <p>Name: {{school_details.name}}</p>
  <p>Principal: {{school_details.principal}}</p>
  <p>Location: {{school_details.location}}</p>
  <h3>Students:</h3>
  {% for student in school_details.students.all %} <!--.students pq es el related_name del modelo Student con School-->
    <p>{{student.name}} who is {{student.age}} years old</p>
  {% endfor %}

</div>

<div class="container">
  
    <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_details.pk %}">Update</a></p>
    <p><a class='btn btn-danger' href="{% url 'basic_app:delete' pk=school_details.pk %}">Delete</a></p>

</div>
{% endblock %}

advance/basic_app/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app_base.html' %}
{% block body_block %}
<div class="jumbotron">
  <h1>
{% if not form.instance.pk %}  <!--Verifica si la instancia e la primary key existe o no. Si no existe significa que es una escuela nueva-->
Create School
{% else %}
Update School
{% endif %}
  </h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" class="btn btn-primary" value="Submit">
  </form>
</div>

{% endblock %}

advance/basic_app/templates/basic_app/school_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %}
<div class="jumbotron">
<h1>Welcome to a list of all school</h1>
<ol>
  {% for school in schools %}
  <h2> <li> <a href="{{school.id}}">{{school.name}}</a></li> </h2>
  {% endfor %}
</ol>
</div>
{% endblock %}

advance/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <title></title>
  </head>
  <body>

    <nav class = "navbar navbar-default navbar-static-top">
      <ul class = "nav navbar-nav">
        <li><a class="navbar-brand" href = "{% url 'basic_app:list' %}">School</a></li> <!--url app:name del link creado en urls-->
        <li><a class="navbar-brand" href = "{% url 'admin:index' %}">Admin</a></li>

      </ul>

    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}

    </div>

  </body>
</html>

advance/templates/index.html
{% extends "base.html" %}
{% block body_block %}
<div class="jumbotron">
  <h1>Home Page!</h1>
</div>
{% endblock %}